// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsUpWRxvCf_w5IQRZb8gtMLuAkAkRkv3A',
    appId: '1:1057117435840:web:8665b865058a375b34ba25',
    messagingSenderId: '1057117435840',
    projectId: 'intership-db0d0',
    authDomain: 'intership-db0d0.firebaseapp.com',
    storageBucket: 'intership-db0d0.firebasestorage.app',
    measurementId: 'G-Q0BSQDRZ50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLWnGYPHvQG3P3yIJGUBO56Cf7YoAK4_c',
    appId: '1:1057117435840:android:c63092800a06b47f34ba25',
    messagingSenderId: '1057117435840',
    projectId: 'intership-db0d0',
    storageBucket: 'intership-db0d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQpqHIXCTqqMJCmGDSR3S6HmYLWmGsVtw',
    appId: '1:1057117435840:ios:83b06a8cfeaa2aa834ba25',
    messagingSenderId: '1057117435840',
    projectId: 'intership-db0d0',
    storageBucket: 'intership-db0d0.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQpqHIXCTqqMJCmGDSR3S6HmYLWmGsVtw',
    appId: '1:1057117435840:ios:83b06a8cfeaa2aa834ba25',
    messagingSenderId: '1057117435840',
    projectId: 'intership-db0d0',
    storageBucket: 'intership-db0d0.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsUpWRxvCf_w5IQRZb8gtMLuAkAkRkv3A',
    appId: '1:1057117435840:web:215d2727fb0beb4d34ba25',
    messagingSenderId: '1057117435840',
    projectId: 'intership-db0d0',
    authDomain: 'intership-db0d0.firebaseapp.com',
    storageBucket: 'intership-db0d0.firebasestorage.app',
    measurementId: 'G-YW1TRBFDZD',
  );
}
